remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: What did I just click on?
description: This ad is being ran by students performing a study at the Georgia Institute of Technology.
